# Generated by Django 5.0.2 on 2024-03-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='password',
        ),
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
    ]
